<?php

namespace Secyt\Core\Proxies\__CG__\Secyt\Core\model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Unidad extends \Secyt\Core\model\Unidad implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'padre', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'hijos', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'nombre', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'sigla', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'direccion', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'mail', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'telefono', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'facultad', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'tipounidad'];
        }

        return ['__isInitialized__', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'padre', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'hijos', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'nombre', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'sigla', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'direccion', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'mail', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'telefono', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'facultad', '' . "\0" . 'Secyt\\Core\\model\\Unidad' . "\0" . 'tipounidad'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Unidad $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getPadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPadre', []);

        return parent::getPadre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPadre($padre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPadre', [$padre]);

        return parent::setPadre($padre);
    }

    /**
     * {@inheritDoc}
     */
    public function getHijos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHijos', []);

        return parent::getHijos();
    }

    /**
     * {@inheritDoc}
     */
    public function setHijos($hijos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHijos', [$hijos]);

        return parent::setHijos($hijos);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSigla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSigla', []);

        return parent::getSigla();
    }

    /**
     * {@inheritDoc}
     */
    public function setSigla($sigla)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSigla', [$sigla]);

        return parent::setSigla($sigla);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', []);

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', [$mail]);

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacultad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacultad', []);

        return parent::getFacultad();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacultad($facultad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacultad', [$facultad]);

        return parent::setFacultad($facultad);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipounidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipounidad', []);

        return parent::getTipounidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipounidad($tipounidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipounidad', [$tipounidad]);

        return parent::setTipounidad($tipounidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadSigla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadSigla', []);

        return parent::getUnidadSigla();
    }

    /**
     * {@inheritDoc}
     */
    public function getOid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getOid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOid', []);

        return parent::getOid();
    }

    /**
     * {@inheritDoc}
     */
    public function setOid($oid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOid', [$oid]);

        return parent::setOid($oid);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncrypted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncrypted', []);

        return parent::getEncrypted();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncrypted($encrypted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncrypted', [$encrypted]);

        return parent::setEncrypted($encrypted);
    }

    /**
     * {@inheritDoc}
     */
    public function encrypt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encrypt', []);

        return parent::encrypt();
    }

    /**
     * {@inheritDoc}
     */
    public function decrypt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'decrypt', []);

        return parent::decrypt();
    }

    /**
     * {@inheritDoc}
     */
    public function getManagedEntities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManagedEntities', []);

        return parent::getManagedEntities();
    }

}
